# This workflow will build PRs submitted to the main branch.

name: ğŸ‘· PR Builder

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "LICENSE"
  workflow_dispatch:

# Avoid running multiple builds for the same PR.
concurrency:
  group: pr-builder-${{ github.ref }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  lint:
    name: â¬£ ESLint (STATIC ANALYSIS)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [lts/*]
    steps:
      - name: â¬‡ï¸ Checkout
        id: checkout
        uses: actions/checkout@v2.3.3
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0

      - name: ğŸŸ¢ Setup node
        id: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ³ Set SHAs for Nx
        id: set-shas
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: "main"

      - name: ğŸ¥¡ Setup pnpm
        id: setup-pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: latest
          run_install: false

      - name: ğŸˆ Get pnpm store directory
        id: get-pnpm-cache-dir
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - name: ğŸ”† Cache pnpm modules
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: ${{ steps.get-pnpm-cache-dir.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: ğŸ§© Install Dependencies
        id: install-dependencies
        run: pnpm install

      - name: ğŸ¦„ Lint All Files
        id: lint-with-eslint
        run: pnpm nx affected --target=lint --parallel=3 --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}

  typecheck:
    name: Ê¦ Typecheck (STATIC ANALYSIS)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [lts/*]
    steps:
      - name: â¬‡ï¸ Checkout
        id: checkout
        uses: actions/checkout@v2.3.3
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0

      - name: ğŸŸ¢ Setup node
        id: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ³ Set SHAs for Nx
        id: set-shas
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: "main"

      - name: ğŸ¥¡ Setup pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: latest
          run_install: false

      - name: ğŸˆ Get pnpm store directory
        id: get-pnpm-cache-dir
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - name: ğŸ”† Cache pnpm modules
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: ${{ steps.get-pnpm-cache-dir.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: ğŸ§© Install Dependencies
        id: install-dependencies
        run: pnpm install

      - name: ğŸ—ï¸ Build
        id: build
        run: pnpm build

      - name: â˜„ï¸ Check Type Errors
        run: pnpm nx affected --target=typecheck --parallel=3 --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}

  test:
    name: ğŸ‘¾ Unit Test (TESTING)
    # needs: [lint, typecheck]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [lts/*]
    steps:
      - name: â¬‡ï¸ Checkout
        id: checkout
        uses: actions/checkout@v2.3.3
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0

      - name: ğŸŸ¢ Setup node
        id: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ¥¡ Setup pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: latest
          run_install: false

      - name: ğŸˆ Get pnpm store directory
        id: get-pnpm-cache-dir
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - name: ğŸ”† Cache pnpm modules
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: ${{ steps.get-pnpm-cache-dir.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: ğŸ§© Install Dependencies
        id: install-dependencies
        run: pnpm install

      - name: ğŸ—ï¸ Build
        id: build
        run: pnpm build

      - name: ğŸƒ Run Jest & Collect Coverage
        id: run-jest-test-and-coverage
        run: pnpm test

      - name: Upload `@asgardeo/browser` coverage reports to Codecov
        id: upload-asgardeo-browser-coverage
        uses: codecov/codecov-action@v4.0.1
        with:
          files: ./packages/browser/coverage/coverage-final.json
          flags: "@asgardeo/browser"
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload `@asgardeo/i18n` coverage reports to Codecov
        id: upload-asgardeo-i18n-coverage
        uses: codecov/codecov-action@v4.0.1
        with:
          files: ./packages/i18n/coverage/coverage-final.json
          flags: "@asgardeo/i18n"
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload `@asgardeo/javascript` coverage reports to Codecov
        id: upload-asgardeo-javascript-coverage
        uses: codecov/codecov-action@v4.0.1
        with:
          files: ./packages/javascript/coverage/coverage-final.json
          flags: "@asgardeo/javascript"
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload `@asgardeo/nextjs` coverage reports to Codecov
        id: upload-asgardeo-nextjs-coverage
        uses: codecov/codecov-action@v4.0.1
        with:
          files: ./packages/nextjs/coverage/coverage-final.json
          flags: "@asgardeo/nextjs"
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload `@asgardeo/node` coverage reports to Codecov
        id: upload-asgardeo-node-coverage
        uses: codecov/codecov-action@v4.0.1
        with:
          files: ./packages/node/coverage/coverage-final.json
          flags: "@asgardeo/node"
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload `@asgardeo/nuxt` coverage reports to Codecov
        id: upload-asgardeo-nuxt-coverage
        uses: codecov/codecov-action@v4.0.1
        with:
          files: ./packages/nuxt/coverage/coverage-final.json
          flags: "@asgardeo/nuxt"
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload `@asgardeo/react` coverage reports to Codecov
        id: upload-asgardeo-react-coverage
        uses: codecov/codecov-action@v4.0.1
        with:
          files: ./packages/react/coverage/coverage-final.json
          flags: "@asgardeo/react"
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload `@asgardeo/react-router` coverage reports to Codecov
        id: upload-asgardeo-react-router-coverage
        uses: codecov/codecov-action@v4.0.1
        with:
          files: ./packages/react-router/coverage/coverage-final.json
          flags: "@asgardeo/react-router"
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload `@asgardeo/vue` coverage reports to Codecov
        id: upload-asgardeo-vue-coverage
        uses: codecov/codecov-action@v4.0.1
        with:
          files: ./packages/vue/coverage/coverage-final.json
          flags: "@asgardeo/vue"
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    name: ğŸš§ Build
    # needs: [ lint, typecheck, test ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [lts/*]
    steps:
      - name: â¬‡ï¸ Checkout
        id: checkout
        uses: actions/checkout@v2.3.3

      - name: ğŸŸ¢ Setup node
        id: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: ğŸ¥¡ Setup pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: latest
          run_install: false

      - name: ğŸˆ Get pnpm store directory
        id: get-pnpm-cache-dir
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - name: ğŸ”† Cache pnpm modules
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: ${{ steps.get-pnpm-cache-dir.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: ğŸ§© Install Dependencies
        id: install-dependencies
        run: pnpm install

      - name: ğŸ—ï¸ Build
        id: build
        run: pnpm build
